### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by yharaskrik** [upstash/redis-js#1322]
When using `@upstash/lock` I receive `TypeError: fetch failed` from the `@upstash/redis` package.

```
"TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async HttpClient.request (/usr/src/app/node_modules/@upstash/redis/nodejs.js:134:15)
    at async SetCommand.exec (/usr/src/app/node_modules/@upstash/redis/nodejs.js:381:31)"
```

I am on Fly but cannot connect with `new Redis` when I pass the password and url to it.

**Comment by yharaskrik** [comment]
Looks like the REST endpoints don't exist on Fly currently.
